# Generated by Django 6.0.3 on 2026-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
